SistemaGerenciadorBiblioteca/Controllers/AlunosController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaGerenciadorBiblioteca.Models;
using SistemaGerenciadorBiblioteca.Repositorio;

namespace SistemaGerenciadorBiblioteca.Controllers
{
    public class AlunosController : Controller
    {
        private readonly IAlunosRepositorio _alunosRepositorio;
        public AlunosController(IAlunosRepositorio alunosRepositorio) 
        {
            _alunosRepositorio = alunosRepositorio;
        }
        public IActionResult Index()
        {
            List<AlunosModel> alunos = _alunosRepositorio.BuscarCadastroAluno(); //Busca no banco de dados
            return View(alunos); //retorna para a view
        }

        public ActionResult Adicionar_aluno()
        {
            return View();
        }

        public ActionResult Editar_aluno(int id)
        {
            AlunosModel info = _alunosRepositorio.ListarIdAluno(id);
            return View(info);
        }

        public ActionResult Deletar_aluno(int id)
        {
            AlunosModel info = _alunosRepositorio.ListarIdAluno(id);
            return View(info);
        }
        public ActionResult Delete(int id)
        {
            try
            {
                _alunosRepositorio.Deletar(id);
                TempData["MensagemDeleteSucesso"] = "Cadastro do aluno deletado com sucesso!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemDeleteErro"] = $"Ops, não foi possível deletar o cadastro do aluno. Tente novamente! Detalhe do Erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
        //Posters - Responsável por armazenar e gravar as informações
        [HttpPost]
        public ActionResult Adicionar_aluno(AlunosModel alunos)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _alunosRepositorio.Adicionar(alunos);
                    TempData["MensagemSucesso"] = "Aluno cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["MensagemPreencha"] = "Preencha os campos faltantes!!";
                    return View(alunos);
                }
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possível cadastrar o Aluno. Tente novamente! Detalhe do Erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
        [HttpPost]
        public ActionResult Editar_aluno(AlunosModel alunos)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _alunosRepositorio.Atualizar(alunos);
                    TempData["MensagemEditSucesso"] = "Cadastro do aluno editado com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["MensagemEditPreencha"] = "Preencha os campos faltantes!!";
                    return View(alunos);
                }
            }
            catch (Exception erro)
            {
                TempData["MensagemEditErro"] = $"Ops, não foi possível editar o cadastro do aluno. Tente novamente! Detalhe do Erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

SistemaGerenciadorBiblioteca/Controllers/EmprestimosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaGerenciadorBiblioteca.Data;
using SistemaGerenciadorBiblioteca.Models;
using SistemaGerenciadorBiblioteca.Repositorio;
using SistemaGerenciadorBiblioteca.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;

namespace SistemaGerenciadorBiblioteca.Controllers
{
    public class EmprestimosController : Controller
    {
        private readonly BancoContext _context;

        public EmprestimosController(BancoContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var emprestimos = _context.Emprestimos
                                      .Include(e => e.Livro)
                                      .Include(e => e.Aluno)
                                      .ToList();
            return View(emprestimos);
        }

        [HttpGet]
        public IActionResult Add()
        {
            EmprestimosViewModel model = new EmprestimosViewModel();
            model.ListaLivros = _context.Livros.ToList();
            model.ListaAlunos = _context.Alunos.ToList();
            return View(model);
        }

        [HttpPost]
        public IActionResult Add(EmprestimosViewModel AddEmprestimo)
        {

            var emprestimo = new EmprestimosModel
            {
                Data_Emprestimo = AddEmprestimo.Data_Emprestimo,
                Data_Devolucao = AddEmprestimo.Data_Devolucao,
                Id_aluno = AddEmprestimo.Id_aluno,
                Id_livro = AddEmprestimo.Id_livro
            };

            _context.Emprestimos.Add(emprestimo);
            _context.SaveChanges();
            TempData["MensagemSucesso"] = "Empréstimo cadastrado com sucesso!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var emprestimo = _context.Emprestimos.Find(id);
            if (emprestimo == null)
            {
                return NotFound();
            }

            var model = new EmprestimosViewModel
            {
                Id_emprestimo = emprestimo.Id_emprestimo,
                Data_Emprestimo = emprestimo.Data_Emprestimo,
                Data_Devolucao = emprestimo.Data_Devolucao,
                Id_aluno = emprestimo.Id_aluno,
                Id_livro = emprestimo.Id_livro,
                ListaAlunos = _context.Alunos.ToList(),
                ListaLivros = _context.Livros.ToList()
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(int id, EmprestimosViewModel model)
        {
            var emprestimo = _context.Emprestimos.Find(id);
            if (emprestimo == null)
            {
                return NotFound();
            }

            emprestimo.Data_Emprestimo = model.Data_Emprestimo;
            emprestimo.Data_Devolucao = model.Data_Devolucao;
            emprestimo.Id_aluno = model.Id_aluno;
            emprestimo.Id_livro = model.Id_livro;

            _context.Emprestimos.Update(emprestimo);
            _context.SaveChanges();
            TempData["MensagemEditSucesso"] = "Empréstimo editado com sucesso!";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult ConfirmarDelete(int id)
        {
            var emprestimo = _context.Emprestimos.Find(id);
            if (emprestimo == null)
            {
                return NotFound();
            }

            return View(emprestimo);
        }

        [HttpPost]
        public IActionResult Delete(int id)
        {
            var emprestimo = _context.Emprestimos.Find(id);

            _context.Emprestimos.Remove(emprestimo);
            _context.SaveChanges();
            TempData["MensagemDeleteSucesso"] = "Empréstimo deletado com sucesso!";
            return RedirectToAction("Index");
        }

    }
}

SistemaGerenciadorBiblioteca/Controllers/LivrosController.cs
using Microsoft.AspNetCore.Mvc;
using SistemaGerenciadorBiblioteca.Data;
using SistemaGerenciadorBiblioteca.Models;
using SistemaGerenciadorBiblioteca.Repositorio;

namespace SistemaGerenciadorBiblioteca.Controllers
{
    public class LivrosController : Controller
    {
        private readonly ILivrosRepositorio _livrosRepositorio; //variável privada
        public LivrosController(ILivrosRepositorio livrosRepositorio) //Construtor da Classe com a injeção de dependência
        {
            _livrosRepositorio = livrosRepositorio;
        }

        //Getters - Apenas mostra as informações
        public IActionResult Index()
        {
            List<LivrosModel> livros = _livrosRepositorio.BuscarCadastroLivro(); //Busca no banco de dados
            return View(livros); //retorna para a view
        }

        public ActionResult Adicionar_livro()
        {
            return View();
        }

        public ActionResult Editar_livro(int id)
        {
            LivrosModel info = _livrosRepositorio.ListarporIdLivro(id);
            return View(info);
        }

        public ActionResult Deletar_livro(int id)
        {
            LivrosModel info = _livrosRepositorio.ListarporIdLivro(id);
            return View(info);
        }
        public ActionResult Delete(int id)
        {
            try
            {
                _livrosRepositorio.Deletar(id);
                TempData["MensagemDeleteSucesso"] = "Cadastro do livro deletado com sucesso!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemDeleteErro"] = $"Ops, não foi possível cadastrar o Livro. Tente novamente! Detalhe do Erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }

        //Posters - Responsável por armazenar e gravar as informações
        [HttpPost]
        public ActionResult Adicionar_livro(LivrosModel livros)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _livrosRepositorio.Adicionar(livros);
                    TempData["MensagemSucesso"] = "Livro cadastrado com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["MensagemPreencha"] = "Preencha os campos faltantes!!";
                    return View(livros);
                }

            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não foi possível cadastrar o Livro. Tente novamente! Detalhe do Erro: {erro.Message}";
                return RedirectToAction("Index");
            }

        }
        [HttpPost]
        public ActionResult Editar_livro(LivrosModel livros)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _livrosRepositorio.Atualizar(livros);
                    TempData["MensagemEditSucesso"] = "Cadastro do livro editado com sucesso!";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["MensagemEditPreencha"] = "Preencha os campos faltantes!!";
                    return View(livros);
                }
            }
            catch (Exception erro)
            {
                TempData["MensagemEditErro"] = $"Ops, não foi possível editar o cadastro do livro. Tente novamente! Detalhe do Erro: {erro.Message}";
                return RedirectToAction("Index");
            }


        }
    }
}

SistemaGerenciadorBiblioteca/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Sistema de Gerenciamento de Biblioteca</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SistemaGerenciadorBiblioteca.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.7/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Sistema de Gerenciamento de Biblioteca</a>
                <div class="vr"></div>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livros" asp-action="Index">Livros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Emprestimos" asp-action="Index">Gerenciamento de Empréstimos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Sobre">Sobre o Projeto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Solução desenvolvida voluntariamente por alunos da Universp.
            |
            &copy; 2024 - Sistema de Gerenciamento de Biblioteca - <a asp-area="" asp-controller="Home" asp-action="Privacy">Conheça o Projeto</a>

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.7/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>